name = "LAPM"
uuid = "900d2f21-6802-4fdd-aec4-3593e8a631ba"
version = "1.0.0-DEV"
authors = ["lmiq <lmartine@unicamp.br> and contributors"]

[deps]
MolSimToolkit = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
MolSimToolkit = "1.31.1"
OrderedCollections = "1.8.1"
PDBTools = "3.11.3"
Plots = "1.41.1"
StatsPlots = "0.15.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
