name = "LAPM"
uuid = "900d2f21-6802-4fdd-aec4-3593e8a631ba"
version = "1.0.0-DEV"
authors = ["lmiq <lmartine@unicamp.br> and contributors"]

[deps]
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MolSimToolkit = "054db54f-6694-444d-9bbb-e9ecdbfe77be"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDBTools = "e29189f1-7114-4dbd-93d0-c5673a921a58"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
EasyFit = "0.7.3"
JSON = "1.3.0"
LinearAlgebra = "1"
MolSimToolkit = "1.31.1"
Optim = "1.13.3"
OrderedCollections = "1.8.1"
PDBTools = "3.16.1"
Plots = "1.41.1"
ProgressMeter = "1.11.0"
Statistics = "1"
StatsPlots = "0.15.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
